version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./ui/build:/api/ui
      # redux share
      - ./ui/src/redux:/redux
      - ./api/.babelrc:/redux/.babelrc
      - ./api/node_modules:/redux/node_modules
      - ./ui/src/variables.js:/variables.js
      - ./ui/src/socket.js:/socket.js
      - ./api/.babelrc:/.babelrc
      - ./api/node_modules:/node_modules
    environment:
      - NODE_ENV
      - WS_PORT
      - PORT=$API_PORT
    ports:
      - 3001:3000
      - 4000:4000

  ui:
    build: ./ui
    volumes:
      - ./ui:/ui
    environment:
      - NODE_ENV
      - WS_PORT
      - PORT=$UI_PORT
    ports:
      - 3000:3000

volumes:
  mongo-data:
