version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3001:3000
  
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000

volumes:
  mongo-data: