version: '3'

services:
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./ui/build:/api/ui
      # redux share
      - ./ui/src/redux/action-types.js:/api/ui-action-types.js
      - ./api/.babelrc:/.babelrc
      - ./api/node_modules:/node_modules
    environment:
      - NODE_ENV
      - WS_PORT
      - PORT=$API_PORT
    ports:
      - 8082:$API_PORT
      - $WS_PORT:$WS_PORT

  ui:
    build: ./ui
    volumes:
      - ./ui:/ui
    environment:
      - NODE_ENV
      - WS_PORT
      - PORT=$UI_PORT
