version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  
  api:
    build: ./api
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - NODE_ENV
      - WS_PORT
      - PORT=$API_PORT
    ports:
      - 3001:3000
      - 4000:4000
  
  ui:
    build: ./ui
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    environment:
      - NODE_ENV
      - WS_PORT
      - PORT=$UI_PORT
    ports:
      - 3000:3000

volumes:
  mongo-data: