export const SET_ONLINE_PLAYERS = 'SET_ONLINE_PLAYERS';
export const CREATE_NEW_GAME = 'CREATE_NEW_GAME';
export const RECONNECT_PLAYER = 'RECONNECT_PLAYER';
export const ADD_PLAYER = 'ADD_PLAYER';

export default {
  SET_ONLINE_PLAYERS,
  CREATE_NEW_GAME,
  RECONNECT_PLAYER,
  ADD_PLAYER
};
