export const SET_ONLINE_PLAYERS = 'SET_ONLINE_PLAYERS';
export const SET_GAME_VIEW = 'SET_GAME_VIEW';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const PROMPT_RECONNECT = 'PROMPT_RECONNECT';
export const ABORT_RECONNECT = 'ABORT_RECONNECT';
export const SET_GAMES = 'SET_GAMES';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';

export default {
  SET_ONLINE_PLAYERS,
  SET_GAME_VIEW,
  SET_CURRENT_GAME,
  PROMPT_RECONNECT,
  ABORT_RECONNECT,
  SET_GAMES,
  SET_USERNAME,
  SET_ERROR_MESSAGE,
  REMOVE_ERROR_MESSAGE
};
