export const SET_ONLINE_PLAYERS = 'SET_ONLINE_PLAYERS';
export const SET_GAME_VIEW = 'SET_GAME_VIEW';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const PROMPT_RECONNECT = 'PROMPT_RECONNECT';
export const ABORT_RECONNECT = 'ABORT_RECONNECT';
export const SET_GAMES = 'SET_GAMES';

export default {
  SET_ONLINE_PLAYERS,
  SET_GAME_VIEW,
  SET_CURRENT_GAME,
  PROMPT_RECONNECT,
  ABORT_RECONNECT,
  SET_GAMES
};
